language: cpp
dist: bionic
cache: ccache
compiler: gcc
sudo: true
addons:
  apt:
    packages:
      - cmake
      - x11-utils
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
git:
  depth: 50
  submodules: true
os:
  - linux
before_script:
  sudo apt-get install libsdl2-dev
  sudo apt-get install libsdl2-image-dev
script:
  - sh scripts/build_portable_linux_engine.sh;