language: cpp
cache: ccache
compiler: gcc
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - x11-utils
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - g++-7
git:
  depth: 50
  submodules: true
os:
  - linux

before_script:
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_portable_linux_engine.sh; fi