language: c
cache: ccache
compiler: gcc
sudo: true
addons:
  apt:
    packages:
      - cmake
      - x11-utils
      - libgl1-mesa-dev
git:
  depth: 50
  submodules: true
os:
  - linux

before_script:
  - sh scripts/travis_linux_deps.sh
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_portable_linux_engine.sh; fi