language: cpp
git:
  depth: 50
  submodules: true
jobs:
  include:
  - stage: build
    name: Build for Linux amd64
    os: linux
    dist: bionic
    cache: ccache
    language: cpp
    compiler: gcc
    sudo: true
    addons:
      apt:
        packages:
        - cmake
        - x11-utils
        - libgl1-mesa-dev
        - libegl1-mesa-dev
        - libgles2-mesa-dev
    before_script:
    - export ARCH=x86_64
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
    script:
    - sh scripts/build_portable_linux_engine.sh;
  - stage: build
    name: Build for macOS
    cache: ccache
    os: osx
    language: cpp
    compiler: clang
    before_script:
    - curl -s https://www.libsdl.org/release/SDL2-2.0.10.dmg > SDL2.dmg
    - hdiutil attach SDL2.dmg
    - mkdir -p ~/Library/Frameworks
    - cp -r /Volumes/SDL2/SDL2.framework ~/Library/Frameworks/
    script:
    - sh scripts/build_osx_engine.sh;
  - stage: build
    name: Build for iOS and deploy
    osx_image: xcode11
    language: objective-c
    before_script:
    - curl -s http://libsdl.org/release/SDL2-2.0.10.tar.gz > SDL2.tar.gz
    - tar xzf SDL2.tar.gz
    - mv SDL2-2.0.10 SDL2
    script:
    - set -o pipefail && xcodebuild -project Xcode-iOS/CSMoE-iOS.xcodeproj -scheme CSMoE-iOS build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
    - mkdir -p Payload
    - cp -a Xcode-iOS/build/Release-iphoneos/csmoe-ios.app Payload/
    - zip -r CSMoE-CD-iOS-universal-unsigned.ipa Payload
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "CSMoE-Deployer"
      - git config --local user.email "824395314@qq.com"
      - export TRAVIS_TAG=continuous
      - git tag --force $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - CSMoE-CD-iOS-universal-unsigned.ipa
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
  - stage: build
    name: Build for Android and deploy
    language: android
    dist: trusty
    android:
      components:
      - build-tools-28.0.3
      - android-29
      - extra
      - add-on
      - tools
    before_script:
    - echo y | /usr/local/android-sdk/tools/bin/sdkmanager "patcher;v4"
    - echo y | /usr/local/android-sdk/tools/bin/sdkmanager ndk-bundle
    script:
    - cd Android
    - "./gradlew assembleRelease"
    - cd ..
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "CSMoE-Deployer"
      - git config --local user.email "824395314@qq.com"
      - export TRAVIS_TAG=continuous
      - git tag --force $TRAVIS_TAG
      - cp Android/app/build/outputs/apk/release/app-release-unsigned.apk CSMoE-CD-Android-unsigned.apk
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - CSMoE-CD-Android-arm64-unsigned.apk
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
  - stage: build
    name: Build for Windows MSVC
    cache: ccache
    os: windows
    language: cpp
    before_script:
    - curl http://libsdl.org/release/SDL2-devel-2.0.10-VC.zip -o SDL2.zip
    - unzip SDL2.zip
    - mv SDL2-2.0.10 SDL2
    script:
    - sh scripts/build_windows_engine.sh
